type ErrorCode =
  | "ERR_NF"
  | "ERR_VALID"
  | "ERR_EV"
  | "ERR_TOKEN_REQUIRED"
  | "ERR_INVALID_PAYLOAD"
  | "ERR_TOKEN_EXPIRED"
  | "ERR_TOKEN_NOT_ACTIVE"
  | "ERR_INVALID_TOKEN"
  | "ERR_TOKEN_VERIFICATION";
