export type ErrorCode =
  | "ERR_NOT_FOUND"
  | "ERR_VALIDATION_FAILED"
  | "ERR_EMAIL_ALREADY_VERIFIED"
  | "ERR_TOKEN_REQUIRED"
  | "ERR_INVALID_PAYLOAD"
  | "ERR_TOKEN_EXPIRED"
  | "ERR_TOKEN_NOT_ACTIVE"
  | "ERR_INVALID_TOKEN"
  | "ERR_TOKEN_VERIFICATION"
  | "ERR_VALIDATION"
  | "ERR_AUTH";
